// api/meli-ventas.js
// Trae las ordenes reales del vendedor desde MercadoLibre.
// Calcula ganancia neta real por venta cruzando con costos propios de Supabase.
// Endpoint: GET /api/meli-ventas?user_id=X&dias=30
//
// Ganancia neta = precio_venta - comision_meli - costo_envio - costo_producto - embalaje

import { getValidToken } from './meli-refresh.js';

const SUPABASE_URL = 'https://qglieqpcmmffgxijbysb.supabase.co';
const MELI_API = 'https://api.mercadolibre.com';

function cors(res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
    res.setHeader('Access-Control-Allow-Methods', 'GET,OPTIONS');
      res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
      }

      // -----------------------------------------------
      // Helpers Supabase
      // -----------------------------------------------

      async function getCostoProducto(userId, meliItemId) {
        const key = process.env.SUPABASE_SERVICE_KEY;
          const res = await fetch(
              `${SUPABASE_URL}/rest/v1/productos_costos?user_id=eq.${encodeURIComponent(userId)}&meli_item_id=eq.${encodeURIComponent(meliItemId)}&select=costo_usd,costo_embalaje_ars&limit=1`,
                  { headers: { apikey: key, Authorization: `Bearer ${key}` } }
                    );
                      const rows = await res.json();
                        return rows[0] || null;
                        }

                        async function getClienteConfig(userId) {
                          const key = process.env.SUPABASE_SERVICE_KEY;
                            const res = await fetch(
                                `${SUPABASE_URL}/rest/v1/clientes?user_id=eq.${encodeURIComponent(userId)}&select=tipo_cambio_usd&limit=1`,
                                    { headers: { apikey: key, Authorization: `Bearer ${key}` } }
                                      );
                                        const rows = await res.json();
                                          return rows[0] || { tipo_cambio_usd: 1250 };
                                          }

                                          async function saveVentaCache(userId, venta) {
                                            const key = process.env.SUPABASE_SERVICE_KEY;
                                              await fetch(`${SUPABASE_URL}/rest/v1/ventas_cache`, {
                                                  method: 'POST',
                                                      headers: {
                                                            apikey: key,
                                                                  Authorization: `Bearer ${key}`,
                                                                        'Content-Type': 'application/json',
                                                                              Prefer: 'resolution=merge-duplicates'
                                                                                  },
                                                                                      body: JSON.stringify(venta)
                                                                                        });
                                                                                        }

                                                                                        // -----------------------------------------------
                                                                                        // Helpers MeLi
                                                                                        // -----------------------------------------------

                                                                                        async function getMeliUserId(token) {
                                                                                          const res = await fetch(`${MELI_API}/users/me`, {
                                                                                              headers: { Authorization: `Bearer ${token}` }
                                                                                                });
                                                                                                  const data = await res.json();
                                                                                                    return data.id;
                                                                                                    }
                                                                                                    
                                                                                                    async function getOrdenes(token, meliUserId, fechaDesde) {
                                                                                                      const url = `${MELI_API}/orders/search?seller=${meliUserId}&order.status=paid&order.date_created.from=${fechaDesde}&limit=50&sort=date_desc`;
                                                                                                        const res = await fetch(url, {
                                                                                                            headers: { Authorization: `Bearer ${token}` }
                                                                                                              });
                                                                                                                const data = await res.json();
                                                                                                                  return data.results || [];
                                                                                                                  }
                                                                                                                  
                                                                                                                  async function getEnvioInfo(token, shipmentId) {
                                                                                                                    if (!shipmentId) return 0;
                                                                                                                      try {
                                                                                                                          const res = await fetch(`${MELI_API}/shipments/${shipmentId}`, {
                                                                                                                                headers: { Authorization: `Bearer ${token}` }
                                                                                                                                    });
                                                                                                                                        const data = await res.json();
                                                                                                                                            // base_cost es lo que paga el vendedor por el envio
                                                                                                                                                return data.shipping_option?.cost || 0;
                                                                                                                                                  } catch {
                                                                                                                                                      return 0;
                                                                                                                                                        }
                                                                                                                                                        }
                                                                                                                                                        
                                                                                                                                                        // -----------------------------------------------
                                                                                                                                                        // Calculos de comision MeLi (aproximacion oficial)
                                                                                                                                                        // -----------------------------------------------
                                                                                                                                                        
                                                                                                                                                        function calcularComision(precio, listingType) {
                                                                                                                                                          // Comisiones aproximadas segun tipo de publicacion MLA 2024
                                                                                                                                                            const tasas = {
                                                                                                                                                                gold_special: 0.1325,  // Classic
                                                                                                                                                                    gold_pro: 0.1325,      // Premium
                                                                                                                                                                        gold: 0.10,
                                                                                                                                                                            silver: 0.06,
                                                                                                                                                                                bronze: 0,
                                                                                                                                                                                    free: 0
                                                                                                                                                                                      };
                                                                                                                                                                                        const tasa = tasas[listingType] || 0.1325;
                                                                                                                                                                                          const comision = precio * tasa;
                                                                                                                                                                                            // Cargo fijo por operacion si aplica
                                                                                                                                                                                              const cargoFijo = precio >= 6900 ? 499 : 0;
                                                                                                                                                                                                return Math.round(comision + cargoFijo);
                                                                                                                                                                                                }
                                                                                                                                                                                                
                                                                                                                                                                                                // -----------------------------------------------
                                                                                                                                                                                                // Handler principal
                                                                                                                                                                                                // -----------------------------------------------
                                                                                                                                                                                                
                                                                                                                                                                                                export default async function handler(req, res) {
                                                                                                                                                                                                  cors(res);
                                                                                                                                                                                                    if (req.method === 'OPTIONS') return res.status(200).end();
                                                                                                                                                                                                    
                                                                                                                                                                                                      const { user_id, dias = '30' } = req.query;
                                                                                                                                                                                                        if (!user_id) return res.status(400).json({ error: 'user_id requerido' });
                                                                                                                                                                                                        
                                                                                                                                                                                                          try {
                                                                                                                                                                                                              // 1. Obtener token valido (con auto-refresh)
                                                                                                                                                                                                                  const token = await getValidToken(user_id);
                                                                                                                                                                                                                  
                                                                                                                                                                                                                      // 2. Obtener meli_user_id del vendedor
                                                                                                                                                                                                                          const meliUserId = await getMeliUserId(token);
                                                                                                                                                                                                                          
                                                                                                                                                                                                                              // 3. Calcular fecha de inicio del periodo
                                                                                                                                                                                                                                  const diasNum = Math.min(parseInt(dias) || 30, 90);
                                                                                                                                                                                                                                      const fechaDesde = new Date(Date.now() - diasNum * 86400000).toISOString();
                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                          // 4. Configuracion del cliente (tipo de cambio)
                                                                                                                                                                                                                                              const config = await getClienteConfig(user_id);
                                                                                                                                                                                                                                                  const tipoCambio = parseFloat(config.tipo_cambio_usd) || 1250;
                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                      // 5. Traer ordenes de MeLi
                                                                                                                                                                                                                                                          const ordenes = await getOrdenes(token, meliUserId, fechaDesde);
                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                              // 6. Procesar cada orden
                                                                                                                                                                                                                                                                  const ventas = [];
                                                                                                                                                                                                                                                                      let totalIngresos = 0;
                                                                                                                                                                                                                                                                          let totalComisiones = 0;
                                                                                                                                                                                                                                                                              let totalEnvios = 0;
                                                                                                                                                                                                                                                                                  let totalGananciasBruta = 0;
                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                      for (const orden of ordenes) {
                                                                                                                                                                                                                                                                                            const item = orden.order_items?.[0];
                                                                                                                                                                                                                                                                                                  if (!item) continue;
                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                        const meliItemId = item.item?.id || '';
                                                                                                                                                                                                                                                                                                              const titulo = item.item?.title || 'Sin titulo';
                                                                                                                                                                                                                                                                                                                    const cantidad = item.quantity || 1;
                                                                                                                                                                                                                                                                                                                          const precioVenta = parseFloat(orden.total_amount) || 0;
                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                // Comision estimada
                                                                                                                                                                                                                                                                                                                                      const listingType = item.listing_type_id || 'gold_special';
                                                                                                                                                                                                                                                                                                                                            const comisionMeli = calcularComision(precioVenta, listingType);
                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                  // Costo de envio
                                                                                                                                                                                                                                                                                                                                                        const costoEnvio = await getEnvioInfo(token, orden.shipping?.id);
                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                              // Costo propio del producto (si esta cargado)
                                                                                                                                                                                                                                                                                                                                                                    const costoData = await getCostoProducto(user_id, meliItemId);
                                                                                                                                                                                                                                                                                                                                                                          const costoProductoARS = costoData
                                                                                                                                                                                                                                                                                                                                                                                  ? parseFloat(costoData.costo_usd) * tipoCambio * cantidad
                                                                                                                                                                                                                                                                                                                                                                                          : 0;
                                                                                                                                                                                                                                                                                                                                                                                                const costoEmbalajeARS = costoData
                                                                                                                                                                                                                                                                                                                                                                                                        ? parseFloat(costoData.costo_embalaje_ars) * cantidad
                                                                                                                                                                                                                                                                                                                                                                                                                : 0;
                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                      // Ganancia neta
                                                                                                                                                                                                                                                                                                                                                                                                                            const ingresoBruto = precioVenta - comisionMeli - costoEnvio;
                                                                                                                                                                                                                                                                                                                                                                                                                                  const gananciaNeta = ingresoBruto - costoProductoARS - costoEmbalajeARS;
                                                                                                                                                                                                                                                                                                                                                                                                                                        const margenPct = precioVenta > 0
                                                                                                                                                                                                                                                                                                                                                                                                                                                ? Math.round((gananciaNeta / precioVenta) * 100)
                                                                                                                                                                                                                                                                                                                                                                                                                                                        : 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                              const ventaObj = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      user_id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              meli_order_id: String(orden.id),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      fecha_venta: orden.date_created,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              meli_item_id: meliItemId,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      titulo,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              cantidad,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      precio_venta: precioVenta,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              comision_meli: comisionMeli,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      costo_envio: costoEnvio,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ingreso_neto: gananciaNeta,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      raw_data: { listing_type: listingType, costo_producto_ars: costoProductoARS }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  // Guardar en cache (upsert)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        await saveVentaCache(user_id, ventaObj);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ventas.push({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      orden_id: orden.id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              fecha: orden.date_created,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      item_id: meliItemId,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              titulo,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      cantidad,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              precio_venta: precioVenta,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      comision_meli: comisionMeli,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              costo_envio: costoEnvio,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      costo_producto_ars: costoProductoARS,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              costo_embalaje_ars: costoEmbalajeARS,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ganancia_neta: Math.round(gananciaNeta),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              margen_pct: margenPct,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      tiene_costo_cargado: !!costoData
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  totalIngresos += precioVenta;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        totalComisiones += comisionMeli;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              totalEnvios += costoEnvio;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    totalGananciasBruta += gananciaNeta;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // 7. Resumen del periodo
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const resumen = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      periodo_dias: diasNum,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            fecha_desde: fechaDesde,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  total_ordenes: ventas.length,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        total_ingresos_ars: Math.round(totalIngresos),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              total_comisiones_ars: Math.round(totalComisiones),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    total_envios_ars: Math.round(totalEnvios),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ganancia_bruta_ars: Math.round(totalGananciasBruta),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                productos_sin_costo: ventas.filter(v => !v.tiene_costo_cargado).length,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      tipo_cambio_usado: tipoCambio
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return res.status(200).json({ success: true, resumen, ventas });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    console.error('meli-ventas error:', err.message);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return res.status(500).json({ error: err.message });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
