// api/meli-ventas.js
// Trae las ordenes reales del vendedor desde MercadoLibre.
// Calcula ganancia neta real por venta cruzando con costos propios de Supabase.
// Endpoint: GET /api/meli-ventas?user_id=X&dias=30
//
// Ganancia neta = precio_venta - comision_meli - costo_envio - costo_producto - embalaje

import { getValidToken } from './meli-refresh.js';

const SUPABASE_URL = 'https://qglieqpcmmffgxijbysb.supabase.co';
const MELI_API = 'https://api.mercadolibre.com';

function cors(res) {
  res.setHeader('Access-Control-Allow-Origin', process.env.ALLOWED_ORIGIN || 'https://productfinder-ia.vercel.app');
    res.setHeader('Access-Control-Allow-Methods', 'GET,OPTIONS');
      res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
      }

      // -----------------------------------------------
      // Helpers Supabase
      // -----------------------------------------------

      async function getCostoProducto(userId, meliItemId) {
        const key = process.env.SUPABASE_SERVICE_KEY;
          const res = await fetch(
              `${SUPABASE_URL}/rest/v1/productos_costos?user_id=eq.${encodeURIComponent(userId)}&meli_item_id=eq.${encodeURIComponent(meliItemId)}&select=costo_usd,costo_embalaje_ars&limit=1`,
                  { headers: { apikey: key, Authorization: `Bearer ${key}` } }
                    );
                      const rows = await res.json();
                        return rows[0] || null;
                        }

                        async function getClienteConfig(userId) {
                          const key = process.env.SUPABASE_SERVICE_KEY;
                            const res = await fetch(
                                `${SUPABASE_URL}/rest/v1/clientes?user_id=eq.${encodeURIComponent(userId)}&select=tipo_cambio_usd&limit=1`,
                                    { headers: { apikey: key, Authorization: `Bearer ${key}` } }
                                      );
                                        const rows = await res.json();
                                          return rows[0] || { tipo_cambio_usd: 1250 };
                                          }

                                          async function saveVentaCache(userId, venta) {
                                            const key = process.env.SUPABASE_SERVICE_KEY;
                                              await fetch(`${SUPABASE_URL}/rest/v1/ventas_cache`, {
                                                  method: 'POST',
                                                      headers: {
                                                            apikey: key,
                                                                  Authorization: `Bearer ${key}`,
                                                                        'Content-Type': 'application/json',
                                                                              Prefer: 'resolution=merge-duplicates'
                                                                                  },
                                                                                      body: JSON.stringify(venta)
                                                                                        });
                                                                                        }

                                                                                        // -----------------------------------------------
                                                                                        // Helpers MeLi
                                                                                        // -----------------------------------------------

                                                                                        async function getMeliUserId(token) {
                                                                                          const res = await fetch(`${MELI_API}/users/me`, {
                                                                                              headers: { Authorization: `Bearer ${token}` }
                                                                                                });
                                                                                                  const data = await res.json();
                                                                                                    return data.id;
                                                                                                    }
                                                                                                    
// MercadoLibre documenta la fecha con offset horario
// (2026-08-01T00:00:00.000-00:00). Con el sufijo Z que devuelve toISOString()
// el filtro puede quedar sin aplicarse y la busqueda vuelve vacia.
function fechaParaMeli(iso) {
  return String(iso).replace(/\.(\d{3})Z$/, '.$1-00:00');
}

function urlDeOrdenes(meliUserId, opciones) {
  const o = opciones || {};
  let url = MELI_API + '/orders/search?seller=' + meliUserId + '&limit=50&sort=date_desc';
  if (o.estado) url += '&order.status=' + encodeURIComponent(o.estado);
  if (o.desde) url += '&order.date_created.from=' + encodeURIComponent(o.desde);
  return url;
}

// La fecha de una orden, mirando todos los campos donde MercadoLibre la puede
// poner. Si el recorte lee un solo campo y ese campo no viene, se descartan
// todas las ventas y el dashboard queda en cero sin decir por que.
function fechaDeOrden(orden) {
  const candidatos = [
    orden && orden.date_created,
    orden && orden.date_closed,
    orden && orden.last_updated,
    orden && orden.payments && orden.payments[0] && orden.payments[0].date_created,
    orden && orden.order_items && orden.order_items[0] && orden.order_items[0].date_created
  ];
  for (const c of candidatos) {
    const t = c ? new Date(c).getTime() : 0;
    if (t && !isNaN(t)) return t;
  }
  return 0;
}

// Medido contra la cuenta real: cualquier consulta con order.date_created.from
// devuelve 0, con Z o con offset, con filtro de estado o sin el. Sin ese
// parametro, la misma cuenta devuelve 20 ordenes pagadas y 23 en total. O sea
// que el filtro de fecha de MercadoLibre no se puede usar: se piden las
// ordenes ordenadas por fecha y se recorta el periodo aca.
async function getOrdenes(token, meliUserId, fechaDesde) {
  const corte = new Date(fechaDesde).getTime();
  const porPagina = 50;
  const maximo = 200;   // 4 paginas: suficiente para un mes de ventas
  const todas = [];

  for (let offset = 0; offset < maximo; offset += porPagina) {
    const res = await fetch(
      urlDeOrdenes(meliUserId, { estado: 'paid' }) + '&offset=' + offset,
      { headers: { Authorization: 'Bearer ' + token } }
    );
    if (!res.ok) break;
    const data = await res.json().catch(() => null);
    const pagina = (data && Array.isArray(data.results)) ? data.results : [];
    todas.push(...pagina);
    if (pagina.length < porPagina) break;
  }

  // El recorte se hace aca y no se confia en el orden que devuelva MeLi.
  // Una orden sin ninguna fecha legible se incluye igual y queda marcada: es
  // preferible mostrarla senalada a hacerla desaparecer en silencio.
  return todas.filter(o => {
    const f = fechaDeOrden(o);
    if (!f) { if (o) o._sin_fecha = true; return true; }
    return f >= corte;
  });
}

// Prueba varias formas de pedir las ordenes y devuelve cuantas trae cada una.
// Sirve para distinguir "no hubo ventas" de "la consulta esta mal armada", que
// desde afuera se ven igual: cero.
async function diagnosticoOrdenes(token, meliUserId, fechaDesde) {
  const variantes = {
    como_lo_pide_la_app: { estado: 'paid', desde: fechaParaMeli(fechaDesde) },
    con_Z_como_antes: { estado: 'paid', desde: fechaDesde },
    sin_filtro_de_estado: { desde: fechaParaMeli(fechaDesde) },
    sin_filtro_de_fecha: { estado: 'paid' },
    todo_el_historial: {}
  };
  const salida = {};
  for (const [nombre, opciones] of Object.entries(variantes)) {
    try {
      const r = await fetch(urlDeOrdenes(meliUserId, opciones), {
        headers: { Authorization: 'Bearer ' + token }
      });
      const j = await r.json().catch(() => null);
      const filas = (j && Array.isArray(j.results)) ? j.results : [];
      salida[nombre] = {
        status: r.status,
        total: (j && j.paging && j.paging.total != null) ? j.paging.total : null,
        devueltas: filas.length,
        mensaje: (j && (j.message || j.error)) || undefined
      };
      // Las fechas de las primeras ordenes: dicen si las ventas son viejas o
      // si el campo de fecha no es el que estamos leyendo. Sin esto, las dos
      // situaciones terminan en el mismo cero.
      if (filas.length) {
        salida[nombre].fechas = filas.slice(0, 5).map(o => ({
          date_created: o && o.date_created,
          date_closed: o && o.date_closed,
          estado: o && o.status,
          monto: o && o.total_amount
        }));
        salida[nombre].campos_de_una_orden = Object.keys(filas[0] || {}).slice(0, 20);
      }
    } catch (e) {
      salida[nombre] = { error: String((e && e.message) || e).slice(0, 120) };
    }
  }
  return salida;
}
                                                                                                                  
                                                                                                                  async function getEnvioInfo(token, shipmentId) {
                                                                                                                    if (!shipmentId) return 0;
                                                                                                                      try {
                                                                                                                          const res = await fetch(`${MELI_API}/shipments/${shipmentId}`, {
                                                                                                                                headers: { Authorization: `Bearer ${token}` }
                                                                                                                                    });
                                                                                                                                        const data = await res.json();
                                                                                                                                            // base_cost es lo que paga el vendedor por el envio
                                                                                                                                                return data.shipping_option?.cost || 0;
                                                                                                                                                  } catch {
                                                                                                                                                      return 0;
                                                                                                                                                        }
                                                                                                                                                        }
                                                                                                                                                        
                                                                                                                                                        // -----------------------------------------------
                                                                                                                                                        // Calculos de comision MeLi (aproximacion oficial)
                                                                                                                                                        // -----------------------------------------------
                                                                                                                                                        
                                                                                                                                                        function calcularComision(precio, listingType) {
                                                                                                                                                          // Comisiones aproximadas segun tipo de publicacion MLA 2024
                                                                                                                                                            const tasas = {
                                                                                                                                                                gold_special: 0.1325,  // Classic
                                                                                                                                                                    gold_pro: 0.1325,      // Premium
                                                                                                                                                                        gold: 0.10,
                                                                                                                                                                            silver: 0.06,
                                                                                                                                                                                bronze: 0,
                                                                                                                                                                                    free: 0
                                                                                                                                                                                      };
                                                                                                                                                                                        const tasa = tasas[listingType] || 0.1325;
                                                                                                                                                                                          const comision = precio * tasa;
                                                                                                                                                                                            // Cargo fijo por operacion si aplica
                                                                                                                                                                                              const cargoFijo = precio >= 6900 ? 499 : 0;
                                                                                                                                                                                                return Math.round(comision + cargoFijo);
                                                                                                                                                                                                }
                                                                                                                                                                                                
                                                                                                                                                                                                // -----------------------------------------------
                                                                                                                                                                                                // Handler principal
                                                                                                                                                                                                // -----------------------------------------------
                                                                                                                                                                                                
                                                                                                                                                                                                export default async function handler(req, res) {
                                                                                                                                                                                                  cors(res);
                                                                                                                                                                                                    if (req.method === 'OPTIONS') return res.status(200).end();
                                                                                                                                                                                                    
                                                                                                                                                                                                      const { user_id, dias = '30' } = req.query;
                                                                                                                                                                                                        if (!user_id) return res.status(400).json({ error: 'user_id requerido' });
                                                                                                                                                                                                        
                                                                                                                                                                                                          try {
                                                                                                                                                                                                              // 1. Obtener token valido (con auto-refresh)
                                                                                                                                                                                                                  const token = await getValidToken(user_id);
                                                                                                                                                                                                                  
                                                                                                                                                                                                                      // 2. Obtener meli_user_id del vendedor
                                                                                                                                                                                                                          const meliUserId = await getMeliUserId(token);
                                                                                                                                                                                                                          
                                                                                                                                                                                                                              // 3. Calcular fecha de inicio del periodo
                                                                                                                                                                                                                                  const diasNum = Math.min(parseInt(dias) || 30, 365);
                                                                                                                                                                                                                                      const fechaDesde = new Date(Date.now() - diasNum * 86400000).toISOString();
                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                          // 4. Configuracion del cliente (tipo de cambio)
                                                                                                                                                                                                                                              const config = await getClienteConfig(user_id);
                                                                                                                                                                                                                                                  const tipoCambio = parseFloat(config.tipo_cambio_usd) || 1250;
                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                      // ?diag=1 compara varias formas de pedir las ordenes, para saber si el
    // cero es real o si el filtro esta mal armado. No expone el token.
    if (req.query && req.query.diag) {
      return res.status(200).json({
        user_id_consultado: String(user_id),
        meli_user_id: meliUserId,
        desde: fechaDesde,
        desde_formato_meli: fechaParaMeli(fechaDesde),
        variantes: await diagnosticoOrdenes(token, meliUserId, fechaDesde)
      });
    }

    // 5. Traer ordenes de MeLi
                                                                                                                                                                                                                                                          const ordenes = await getOrdenes(token, meliUserId, fechaDesde);
                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                              // 6. Procesar cada orden
                                                                                                                                                                                                                                                                  const ventas = [];
                                                                                                                                                                                                                                                                      let totalIngresos = 0;
                                                                                                                                                                                                                                                                          let totalComisiones = 0;
                                                                                                                                                                                                                                                                              let totalEnvios = 0;
                                                                                                                                                                                                                                                                                  let totalGananciasBruta = 0;
                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                      for (const orden of ordenes) {
                                                                                                                                                                                                                                                                                            const item = orden.order_items?.[0];
                                                                                                                                                                                                                                                                                                  if (!item) continue;
                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                        const meliItemId = item.item?.id || '';
                                                                                                                                                                                                                                                                                                              const titulo = item.item?.title || 'Sin titulo';
                                                                                                                                                                                                                                                                                                                    const cantidad = item.quantity || 1;
                                                                                                                                                                                                                                                                                                                          const precioVenta = parseFloat(orden.total_amount) || 0;
                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                // Comision estimada
                                                                                                                                                                                                                                                                                                                                      const listingType = item.listing_type_id || 'gold_special';
                                                                                                                                                                                                                                                                                                                                            const comisionMeli = calcularComision(precioVenta, listingType);
                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                  // Costo de envio
                                                                                                                                                                                                                                                                                                                                                        const costoEnvio = await getEnvioInfo(token, orden.shipping?.id);
                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                              // Costo propio del producto (si esta cargado)
                                                                                                                                                                                                                                                                                                                                                                    const costoData = await getCostoProducto(user_id, meliItemId);
                                                                                                                                                                                                                                                                                                                                                                          const costoProductoARS = costoData
                                                                                                                                                                                                                                                                                                                                                                                  ? parseFloat(costoData.costo_usd) * tipoCambio * cantidad
                                                                                                                                                                                                                                                                                                                                                                                          : 0;
                                                                                                                                                                                                                                                                                                                                                                                                const costoEmbalajeARS = costoData
                                                                                                                                                                                                                                                                                                                                                                                                        ? parseFloat(costoData.costo_embalaje_ars) * cantidad
                                                                                                                                                                                                                                                                                                                                                                                                                : 0;
                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                      // Ganancia neta
                                                                                                                                                                                                                                                                                                                                                                                                                            const ingresoBruto = precioVenta - comisionMeli - costoEnvio;
                                                                                                                                                                                                                                                                                                                                                                                                                                  const gananciaNeta = ingresoBruto - costoProductoARS - costoEmbalajeARS;
                                                                                                                                                                                                                                                                                                                                                                                                                                        const margenPct = precioVenta > 0
                                                                                                                                                                                                                                                                                                                                                                                                                                                ? Math.round((gananciaNeta / precioVenta) * 100)
                                                                                                                                                                                                                                                                                                                                                                                                                                                        : 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                              const ventaObj = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      user_id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              meli_order_id: String(orden.id),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      fecha_venta: orden.date_created,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              meli_item_id: meliItemId,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      titulo,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              cantidad,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      precio_venta: precioVenta,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              comision_meli: comisionMeli,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      costo_envio: costoEnvio,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ingreso_neto: gananciaNeta,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      raw_data: { listing_type: listingType, costo_producto_ars: costoProductoARS }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  // Guardar en cache (upsert)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        await saveVentaCache(user_id, ventaObj);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ventas.push({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      orden_id: orden.id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              fecha: orden.date_created || orden.date_closed || orden.last_updated || null,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              fecha_desconocida: !!orden._sin_fecha,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      item_id: meliItemId,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              titulo,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      cantidad,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              precio_venta: precioVenta,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      comision_meli: comisionMeli,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              costo_envio: costoEnvio,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      costo_producto_ars: costoProductoARS,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              costo_embalaje_ars: costoEmbalajeARS,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ganancia_neta: Math.round(gananciaNeta),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              margen_pct: margenPct,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      tiene_costo_cargado: !!costoData
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  totalIngresos += precioVenta;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        totalComisiones += comisionMeli;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              totalEnvios += costoEnvio;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    totalGananciasBruta += gananciaNeta;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // 7. Resumen del periodo
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const resumen = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      periodo_dias: diasNum,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            fecha_desde: fechaDesde,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  total_ordenes: ventas.length,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        total_ingresos_ars: Math.round(totalIngresos),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              total_comisiones_ars: Math.round(totalComisiones),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    total_envios_ars: Math.round(totalEnvios),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ganancia_bruta_ars: Math.round(totalGananciasBruta),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                productos_sin_costo: ventas.filter(v => !v.tiene_costo_cargado).length,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ventas_sin_fecha: ventas.filter(v => v.fecha_desconocida).length,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      tipo_cambio_usado: tipoCambio
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return res.status(200).json({ success: true, resumen, ventas });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    console.error('meli-ventas error:', err.message);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return res.status(500).json({ error: err.message });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
